// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/quiz.proto

package pub_sub_quiz

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuizClient is the client API for Quiz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuizClient interface {
	Play(ctx context.Context, opts ...grpc.CallOption) (Quiz_PlayClient, error)
}

type quizClient struct {
	cc grpc.ClientConnInterface
}

func NewQuizClient(cc grpc.ClientConnInterface) QuizClient {
	return &quizClient{cc}
}

func (c *quizClient) Play(ctx context.Context, opts ...grpc.CallOption) (Quiz_PlayClient, error) {
	stream, err := c.cc.NewStream(ctx, &Quiz_ServiceDesc.Streams[0], "/pubSubQuiz.Quiz/Play", opts...)
	if err != nil {
		return nil, err
	}
	x := &quizPlayClient{stream}
	return x, nil
}

type Quiz_PlayClient interface {
	Send(*PlayRequest) error
	Recv() (*PlayResponse, error)
	grpc.ClientStream
}

type quizPlayClient struct {
	grpc.ClientStream
}

func (x *quizPlayClient) Send(m *PlayRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *quizPlayClient) Recv() (*PlayResponse, error) {
	m := new(PlayResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QuizServer is the server API for Quiz service.
// All implementations must embed UnimplementedQuizServer
// for forward compatibility
type QuizServer interface {
	Play(Quiz_PlayServer) error
	mustEmbedUnimplementedQuizServer()
}

// UnimplementedQuizServer must be embedded to have forward compatible implementations.
type UnimplementedQuizServer struct {
}

func (UnimplementedQuizServer) Play(Quiz_PlayServer) error {
	return status.Errorf(codes.Unimplemented, "method Play not implemented")
}
func (UnimplementedQuizServer) mustEmbedUnimplementedQuizServer() {}

// UnsafeQuizServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuizServer will
// result in compilation errors.
type UnsafeQuizServer interface {
	mustEmbedUnimplementedQuizServer()
}

func RegisterQuizServer(s grpc.ServiceRegistrar, srv QuizServer) {
	s.RegisterService(&Quiz_ServiceDesc, srv)
}

func _Quiz_Play_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(QuizServer).Play(&quizPlayServer{stream})
}

type Quiz_PlayServer interface {
	Send(*PlayResponse) error
	Recv() (*PlayRequest, error)
	grpc.ServerStream
}

type quizPlayServer struct {
	grpc.ServerStream
}

func (x *quizPlayServer) Send(m *PlayResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *quizPlayServer) Recv() (*PlayRequest, error) {
	m := new(PlayRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Quiz_ServiceDesc is the grpc.ServiceDesc for Quiz service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Quiz_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pubSubQuiz.Quiz",
	HandlerType: (*QuizServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Play",
			Handler:       _Quiz_Play_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/quiz.proto",
}
