// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/quiz.proto

package pub_sub_quiz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*PlayRequest_JoinRequest
	//	*PlayRequest_AnswerRequest
	Msg isPlayRequest_Msg `protobuf_oneof:"msg"`
}

func (x *PlayRequest) Reset() {
	*x = PlayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quiz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRequest) ProtoMessage() {}

func (x *PlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRequest.ProtoReflect.Descriptor instead.
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{0}
}

func (m *PlayRequest) GetMsg() isPlayRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *PlayRequest) GetJoinRequest() *PlayRequest_Join {
	if x, ok := x.GetMsg().(*PlayRequest_JoinRequest); ok {
		return x.JoinRequest
	}
	return nil
}

func (x *PlayRequest) GetAnswerRequest() *PlayRequest_Answer {
	if x, ok := x.GetMsg().(*PlayRequest_AnswerRequest); ok {
		return x.AnswerRequest
	}
	return nil
}

type isPlayRequest_Msg interface {
	isPlayRequest_Msg()
}

type PlayRequest_JoinRequest struct {
	JoinRequest *PlayRequest_Join `protobuf:"bytes,1,opt,name=join_request,json=joinRequest,proto3,oneof"`
}

type PlayRequest_AnswerRequest struct {
	AnswerRequest *PlayRequest_Answer `protobuf:"bytes,2,opt,name=answer_request,json=answerRequest,proto3,oneof"`
}

func (*PlayRequest_JoinRequest) isPlayRequest_Msg() {}

func (*PlayRequest_AnswerRequest) isPlayRequest_Msg() {}

type PlayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*PlayResponse_QuestionMsg
	//	*PlayResponse_JoinResponseMsg
	//	*PlayResponse_AnswerRejectionMsg
	//	*PlayResponse_GameEndsMsg
	//	*PlayResponse_GameStartsInMsg
	//	*PlayResponse_StartInterruptedMsg
	Msg isPlayResponse_Msg `protobuf_oneof:"msg"`
}

func (x *PlayResponse) Reset() {
	*x = PlayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quiz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse) ProtoMessage() {}

func (x *PlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse.ProtoReflect.Descriptor instead.
func (*PlayResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1}
}

func (m *PlayResponse) GetMsg() isPlayResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *PlayResponse) GetQuestionMsg() *PlayResponse_QuizQuestion {
	if x, ok := x.GetMsg().(*PlayResponse_QuestionMsg); ok {
		return x.QuestionMsg
	}
	return nil
}

func (x *PlayResponse) GetJoinResponseMsg() *PlayResponse_JoinResponse {
	if x, ok := x.GetMsg().(*PlayResponse_JoinResponseMsg); ok {
		return x.JoinResponseMsg
	}
	return nil
}

func (x *PlayResponse) GetAnswerRejectionMsg() *PlayResponse_AnswerRejected {
	if x, ok := x.GetMsg().(*PlayResponse_AnswerRejectionMsg); ok {
		return x.AnswerRejectionMsg
	}
	return nil
}

func (x *PlayResponse) GetGameEndsMsg() *PlayResponse_GameEnds {
	if x, ok := x.GetMsg().(*PlayResponse_GameEndsMsg); ok {
		return x.GameEndsMsg
	}
	return nil
}

func (x *PlayResponse) GetGameStartsInMsg() *PlayResponse_GameStartsIn {
	if x, ok := x.GetMsg().(*PlayResponse_GameStartsInMsg); ok {
		return x.GameStartsInMsg
	}
	return nil
}

func (x *PlayResponse) GetStartInterruptedMsg() *PlayResponse_StartInterrupted {
	if x, ok := x.GetMsg().(*PlayResponse_StartInterruptedMsg); ok {
		return x.StartInterruptedMsg
	}
	return nil
}

type isPlayResponse_Msg interface {
	isPlayResponse_Msg()
}

type PlayResponse_QuestionMsg struct {
	QuestionMsg *PlayResponse_QuizQuestion `protobuf:"bytes,1,opt,name=questionMsg,proto3,oneof"`
}

type PlayResponse_JoinResponseMsg struct {
	JoinResponseMsg *PlayResponse_JoinResponse `protobuf:"bytes,2,opt,name=joinResponseMsg,proto3,oneof"`
}

type PlayResponse_AnswerRejectionMsg struct {
	AnswerRejectionMsg *PlayResponse_AnswerRejected `protobuf:"bytes,3,opt,name=answerRejectionMsg,proto3,oneof"`
}

type PlayResponse_GameEndsMsg struct {
	GameEndsMsg *PlayResponse_GameEnds `protobuf:"bytes,4,opt,name=gameEndsMsg,proto3,oneof"`
}

type PlayResponse_GameStartsInMsg struct {
	GameStartsInMsg *PlayResponse_GameStartsIn `protobuf:"bytes,5,opt,name=gameStartsInMsg,proto3,oneof"`
}

type PlayResponse_StartInterruptedMsg struct {
	StartInterruptedMsg *PlayResponse_StartInterrupted `protobuf:"bytes,6,opt,name=startInterruptedMsg,proto3,oneof"`
}

func (*PlayResponse_QuestionMsg) isPlayResponse_Msg() {}

func (*PlayResponse_JoinResponseMsg) isPlayResponse_Msg() {}

func (*PlayResponse_AnswerRejectionMsg) isPlayResponse_Msg() {}

func (*PlayResponse_GameEndsMsg) isPlayResponse_Msg() {}

func (*PlayResponse_GameStartsInMsg) isPlayResponse_Msg() {}

func (*PlayResponse_StartInterruptedMsg) isPlayResponse_Msg() {}

type PlayRequest_Join struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayRequest_Join) Reset() {
	*x = PlayRequest_Join{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quiz_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayRequest_Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRequest_Join) ProtoMessage() {}

func (x *PlayRequest_Join) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRequest_Join.ProtoReflect.Descriptor instead.
func (*PlayRequest_Join) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{0, 0}
}

type PlayRequest_Answer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionId string `protobuf:"bytes,1,opt,name=questionId,proto3" json:"questionId,omitempty"`
	Answer     string `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *PlayRequest_Answer) Reset() {
	*x = PlayRequest_Answer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quiz_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayRequest_Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRequest_Answer) ProtoMessage() {}

func (x *PlayRequest_Answer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRequest_Answer.ProtoReflect.Descriptor instead.
func (*PlayRequest_Answer) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PlayRequest_Answer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *PlayRequest_Answer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type PlayResponse_QuizQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionId      string   `protobuf:"bytes,3,opt,name=questionId,proto3" json:"questionId,omitempty"`
	Question        string   `protobuf:"bytes,4,opt,name=question,proto3" json:"question,omitempty"`
	Answers         []string `protobuf:"bytes,5,rep,name=answers,proto3" json:"answers,omitempty"`
	QuestionTimeout float64  `protobuf:"fixed64,6,opt,name=questionTimeout,proto3" json:"questionTimeout,omitempty"`
}

func (x *PlayResponse_QuizQuestion) Reset() {
	*x = PlayResponse_QuizQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quiz_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse_QuizQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse_QuizQuestion) ProtoMessage() {}

func (x *PlayResponse_QuizQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse_QuizQuestion.ProtoReflect.Descriptor instead.
func (*PlayResponse_QuizQuestion) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PlayResponse_QuizQuestion) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *PlayResponse_QuizQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *PlayResponse_QuizQuestion) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *PlayResponse_QuizQuestion) GetQuestionTimeout() float64 {
	if x != nil {
		return x.QuestionTimeout
	}
	return 0
}

type PlayResponse_JoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success        bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason         string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CurrentPlayers int32  `protobuf:"varint,3,opt,name=currentPlayers,proto3" json:"currentPlayers,omitempty"`
	TargetPlayers  int32  `protobuf:"varint,4,opt,name=targetPlayers,proto3" json:"targetPlayers,omitempty"`
	PlayerId       string `protobuf:"bytes,5,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *PlayResponse_JoinResponse) Reset() {
	*x = PlayResponse_JoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quiz_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse_JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse_JoinResponse) ProtoMessage() {}

func (x *PlayResponse_JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse_JoinResponse.ProtoReflect.Descriptor instead.
func (*PlayResponse_JoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1, 1}
}

func (x *PlayResponse_JoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayResponse_JoinResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PlayResponse_JoinResponse) GetCurrentPlayers() int32 {
	if x != nil {
		return x.CurrentPlayers
	}
	return 0
}

func (x *PlayResponse_JoinResponse) GetTargetPlayers() int32 {
	if x != nil {
		return x.TargetPlayers
	}
	return 0
}

func (x *PlayResponse_JoinResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PlayResponse_AnswerRejected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *PlayResponse_AnswerRejected) Reset() {
	*x = PlayResponse_AnswerRejected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quiz_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse_AnswerRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse_AnswerRejected) ProtoMessage() {}

func (x *PlayResponse_AnswerRejected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse_AnswerRejected.ProtoReflect.Descriptor instead.
func (*PlayResponse_AnswerRejected) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1, 2}
}

func (x *PlayResponse_AnswerRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PlayResponse_GameStartsIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecondsUntilStart float64 `protobuf:"fixed64,1,opt,name=secondsUntilStart,proto3" json:"secondsUntilStart,omitempty"`
}

func (x *PlayResponse_GameStartsIn) Reset() {
	*x = PlayResponse_GameStartsIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quiz_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse_GameStartsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse_GameStartsIn) ProtoMessage() {}

func (x *PlayResponse_GameStartsIn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse_GameStartsIn.ProtoReflect.Descriptor instead.
func (*PlayResponse_GameStartsIn) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1, 3}
}

func (x *PlayResponse_GameStartsIn) GetSecondsUntilStart() float64 {
	if x != nil {
		return x.SecondsUntilStart
	}
	return 0
}

type PlayResponse_Score struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Score    int32  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *PlayResponse_Score) Reset() {
	*x = PlayResponse_Score{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quiz_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse_Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse_Score) ProtoMessage() {}

func (x *PlayResponse_Score) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse_Score.ProtoReflect.Descriptor instead.
func (*PlayResponse_Score) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1, 4}
}

func (x *PlayResponse_Score) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayResponse_Score) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type PlayResponse_GameEnds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Leaderboard []*PlayResponse_Score `protobuf:"bytes,1,rep,name=leaderboard,proto3" json:"leaderboard,omitempty"`
}

func (x *PlayResponse_GameEnds) Reset() {
	*x = PlayResponse_GameEnds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quiz_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse_GameEnds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse_GameEnds) ProtoMessage() {}

func (x *PlayResponse_GameEnds) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse_GameEnds.ProtoReflect.Descriptor instead.
func (*PlayResponse_GameEnds) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1, 5}
}

func (x *PlayResponse_GameEnds) GetLeaderboard() []*PlayResponse_Score {
	if x != nil {
		return x.Leaderboard
	}
	return nil
}

type PlayResponse_StartInterrupted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *PlayResponse_StartInterrupted) Reset() {
	*x = PlayResponse_StartInterrupted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_quiz_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse_StartInterrupted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse_StartInterrupted) ProtoMessage() {}

func (x *PlayResponse_StartInterrupted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse_StartInterrupted.ProtoReflect.Descriptor instead.
func (*PlayResponse_StartInterrupted) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1, 6}
}

func (x *PlayResponse_StartInterrupted) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_quiz_proto protoreflect.FileDescriptor

var file_proto_quiz_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x70, 0x75, 0x62, 0x53, 0x75, 0x62, 0x51, 0x75, 0x69, 0x7a, 0x22, 0xea,
	0x01, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41,
	0x0a, 0x0c, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x75, 0x62, 0x53, 0x75, 0x62, 0x51, 0x75, 0x69,
	0x7a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4a, 0x6f,
	0x69, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x47, 0x0a, 0x0e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x75, 0x62, 0x53,
	0x75, 0x62, 0x51, 0x75, 0x69, 0x7a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0d, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x0a, 0x04, 0x4a, 0x6f,
	0x69, 0x6e, 0x1a, 0x40, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xe2, 0x08, 0x0a, 0x0c,
	0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0b,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x70, 0x75, 0x62, 0x53, 0x75, 0x62, 0x51, 0x75, 0x69, 0x7a, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x51, 0x75, 0x69, 0x7a,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x51, 0x0a, 0x0f, 0x6a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x70, 0x75, 0x62, 0x53, 0x75, 0x62, 0x51, 0x75, 0x69, 0x7a, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x6a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x59, 0x0a, 0x12, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x75, 0x62, 0x53, 0x75, 0x62, 0x51,
	0x75, 0x69, 0x7a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48,
	0x00, 0x52, 0x12, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x45, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64,
	0x73, 0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x75, 0x62,
	0x53, 0x75, 0x62, 0x51, 0x75, 0x69, 0x7a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x73, 0x48, 0x00, 0x52,
	0x0b, 0x67, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x51, 0x0a, 0x0f,
	0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x73, 0x49, 0x6e, 0x4d, 0x73, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x75, 0x62, 0x53, 0x75, 0x62, 0x51, 0x75,
	0x69, 0x7a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x73, 0x49, 0x6e, 0x48, 0x00, 0x52, 0x0f,
	0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x73, 0x49, 0x6e, 0x4d, 0x73, 0x67, 0x12,
	0x5d, 0x0a, 0x13, 0x73, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x75, 0x70,
	0x74, 0x65, 0x64, 0x4d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70,
	0x75, 0x62, 0x53, 0x75, 0x62, 0x51, 0x75, 0x69, 0x7a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x72, 0x75, 0x70, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x13, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x75, 0x70, 0x74, 0x65, 0x64, 0x4d, 0x73, 0x67, 0x1a, 0x8e,
	0x01, 0x0a, 0x0c, 0x51, 0x75, 0x69, 0x7a, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x1a,
	0xaa, 0x01, 0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x28, 0x0a, 0x0e,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x1a, 0x3c, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x73, 0x49, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x11, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x1a, 0x39, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x1a,
	0x4c, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x73, 0x12, 0x40, 0x0a, 0x0b, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x70, 0x75, 0x62, 0x53, 0x75, 0x62, 0x51, 0x75, 0x69, 0x7a, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x52, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x1a, 0x2a, 0x0a,
	0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x75, 0x70, 0x74, 0x65,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x32, 0x47, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x3f, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x79,
	0x12, 0x17, 0x2e, 0x70, 0x75, 0x62, 0x53, 0x75, 0x62, 0x51, 0x75, 0x69, 0x7a, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x75, 0x62, 0x53,
	0x75, 0x62, 0x51, 0x75, 0x69, 0x7a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x2f, 0x70,
	0x75, 0x62, 0x2d, 0x73, 0x75, 0x62, 0x2d, 0x71, 0x75, 0x69, 0x7a, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_quiz_proto_rawDescOnce sync.Once
	file_proto_quiz_proto_rawDescData = file_proto_quiz_proto_rawDesc
)

func file_proto_quiz_proto_rawDescGZIP() []byte {
	file_proto_quiz_proto_rawDescOnce.Do(func() {
		file_proto_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_quiz_proto_rawDescData)
	})
	return file_proto_quiz_proto_rawDescData
}

var file_proto_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_quiz_proto_goTypes = []interface{}{
	(*PlayRequest)(nil),                   // 0: pubSubQuiz.PlayRequest
	(*PlayResponse)(nil),                  // 1: pubSubQuiz.PlayResponse
	(*PlayRequest_Join)(nil),              // 2: pubSubQuiz.PlayRequest.Join
	(*PlayRequest_Answer)(nil),            // 3: pubSubQuiz.PlayRequest.Answer
	(*PlayResponse_QuizQuestion)(nil),     // 4: pubSubQuiz.PlayResponse.QuizQuestion
	(*PlayResponse_JoinResponse)(nil),     // 5: pubSubQuiz.PlayResponse.JoinResponse
	(*PlayResponse_AnswerRejected)(nil),   // 6: pubSubQuiz.PlayResponse.AnswerRejected
	(*PlayResponse_GameStartsIn)(nil),     // 7: pubSubQuiz.PlayResponse.GameStartsIn
	(*PlayResponse_Score)(nil),            // 8: pubSubQuiz.PlayResponse.Score
	(*PlayResponse_GameEnds)(nil),         // 9: pubSubQuiz.PlayResponse.GameEnds
	(*PlayResponse_StartInterrupted)(nil), // 10: pubSubQuiz.PlayResponse.StartInterrupted
}
var file_proto_quiz_proto_depIdxs = []int32{
	2,  // 0: pubSubQuiz.PlayRequest.join_request:type_name -> pubSubQuiz.PlayRequest.Join
	3,  // 1: pubSubQuiz.PlayRequest.answer_request:type_name -> pubSubQuiz.PlayRequest.Answer
	4,  // 2: pubSubQuiz.PlayResponse.questionMsg:type_name -> pubSubQuiz.PlayResponse.QuizQuestion
	5,  // 3: pubSubQuiz.PlayResponse.joinResponseMsg:type_name -> pubSubQuiz.PlayResponse.JoinResponse
	6,  // 4: pubSubQuiz.PlayResponse.answerRejectionMsg:type_name -> pubSubQuiz.PlayResponse.AnswerRejected
	9,  // 5: pubSubQuiz.PlayResponse.gameEndsMsg:type_name -> pubSubQuiz.PlayResponse.GameEnds
	7,  // 6: pubSubQuiz.PlayResponse.gameStartsInMsg:type_name -> pubSubQuiz.PlayResponse.GameStartsIn
	10, // 7: pubSubQuiz.PlayResponse.startInterruptedMsg:type_name -> pubSubQuiz.PlayResponse.StartInterrupted
	8,  // 8: pubSubQuiz.PlayResponse.GameEnds.leaderboard:type_name -> pubSubQuiz.PlayResponse.Score
	0,  // 9: pubSubQuiz.Quiz.Play:input_type -> pubSubQuiz.PlayRequest
	1,  // 10: pubSubQuiz.Quiz.Play:output_type -> pubSubQuiz.PlayResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_quiz_proto_init() }
func file_proto_quiz_proto_init() {
	if File_proto_quiz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_quiz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quiz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quiz_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayRequest_Join); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quiz_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayRequest_Answer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quiz_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse_QuizQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quiz_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse_JoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quiz_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse_AnswerRejected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quiz_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse_GameStartsIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quiz_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse_Score); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quiz_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse_GameEnds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_quiz_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse_StartInterrupted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_quiz_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PlayRequest_JoinRequest)(nil),
		(*PlayRequest_AnswerRequest)(nil),
	}
	file_proto_quiz_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PlayResponse_QuestionMsg)(nil),
		(*PlayResponse_JoinResponseMsg)(nil),
		(*PlayResponse_AnswerRejectionMsg)(nil),
		(*PlayResponse_GameEndsMsg)(nil),
		(*PlayResponse_GameStartsInMsg)(nil),
		(*PlayResponse_StartInterruptedMsg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_quiz_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_quiz_proto_goTypes,
		DependencyIndexes: file_proto_quiz_proto_depIdxs,
		MessageInfos:      file_proto_quiz_proto_msgTypes,
	}.Build()
	File_proto_quiz_proto = out.File
	file_proto_quiz_proto_rawDesc = nil
	file_proto_quiz_proto_goTypes = nil
	file_proto_quiz_proto_depIdxs = nil
}
